import { ImpactEntry, RACIRole } from '@/types/entry';
import { generateId } from '@/lib/entries';

export function createSampleEntries(): ImpactEntry[] {
  const now = new Date();
  const d = (daysAgo: number) => {
    const date = new Date(now);
    date.setDate(date.getDate() - daysAgo);
    return date.toISOString().split('T')[0];
  };

  return [
    {
      id: generateId(),
      title: 'Migrated auth service to OAuth 2.0 PKCE flow',
      createdAt: new Date(now.getTime() - 30 * 86400000).toISOString(),
      situation: 'Legacy auth relied on implicit grant flow, flagged in security audit as high-risk. Affected 12 downstream services.',
      task: 'Lead migration to PKCE-based OAuth 2.0 across all client apps with zero downtime.',
      action: 'Designed phased rollout: shadow-mode token validation, gradual traffic shifting via feature flags, coordinated with 3 teams for client SDK upgrades.',
      result: 'Completed migration with 0 incidents. Reduced token theft surface area. Security team signed off on compliance.',
      startDate: d(45),
      endDate: d(12),
      originalEstimateDays: 20,
      actualDays: 33,
      complicatingFactors: 'Two legacy mobile apps had hardcoded implicit flow. Required emergency patches and App Store review cycles.',
      technologies: ['OAuth 2.0', 'PKCE', 'Node.js', 'React Native', 'LaunchDarkly'],
      growthWins: 'First time leading a cross-org security initiative. Built relationship with security team.',
      raci: ['responsible', 'accountable'] as RACIRole[],
      status: 'completed',
      impactLevel: 'critical',
    },
    {
      id: generateId(),
      title: 'Designed and shipped real-time collaboration engine',
      createdAt: new Date(now.getTime() - 20 * 86400000).toISOString(),
      situation: 'Product wanted Google Docs-style collaboration. No existing infrastructure for real-time sync.',
      task: 'Architect and implement CRDT-based sync engine that scales to 100+ concurrent editors.',
      action: 'Evaluated Yjs vs Automerge, chose Yjs for performance. Built WebSocket relay service, integrated with existing REST API layer. Wrote operational transform fallback.',
      result: 'Shipped to beta with 50 concurrent users. P95 sync latency under 120ms. No data conflicts reported.',
      startDate: d(60),
      endDate: d(15),
      originalEstimateDays: 30,
      actualDays: 45,
      complicatingFactors: 'WebSocket infrastructure had to be built from scratch. DevOps team was at capacity, had to self-manage deployment.',
      technologies: ['Yjs', 'WebSockets', 'Redis', 'TypeScript', 'AWS ECS'],
      growthWins: 'Deep expertise in CRDTs. Published internal tech talk that became most-watched in engineering org.',
      raci: ['responsible', 'accountable', 'consulted'] as RACIRole[],
      status: 'completed',
      impactLevel: 'high',
    },
    {
      id: generateId(),
      title: 'Implementing observability platform migration',
      createdAt: new Date(now.getTime() - 10 * 86400000).toISOString(),
      situation: 'Current Datadog spend is $180k/yr and growing. Leadership wants cost reduction without losing visibility.',
      task: 'Migrate to Grafana Cloud + OpenTelemetry stack while maintaining SLO dashboards and alerting.',
      action: 'Set up OTel collectors in staging, migrating services one team at a time. Building Grafana dashboards to match existing Datadog ones. Running both in parallel for validation.',
      result: '',
      startDate: d(10),
      endDate: '',
      originalEstimateDays: 25,
      actualDays: 10,
      complicatingFactors: 'Some teams rely on Datadog-specific APM features (e.g., continuous profiler). Need alternatives.',
      technologies: ['OpenTelemetry', 'Grafana', 'Prometheus', 'Go', 'Kubernetes'],
      growthWins: 'Learning the observability space deeply. Building cost-optimization muscle.',
      raci: ['responsible', 'consulted'] as RACIRole[],
      status: 'in-progress',
      impactLevel: 'high',
    },
    {
      id: generateId(),
      title: 'RFC: API versioning strategy for public APIs',
      createdAt: new Date(now.getTime() - 5 * 86400000).toISOString(),
      situation: 'Company launching public API. No versioning strategy exists. Breaking changes have caused partner churn.',
      task: 'Author RFC proposing versioning strategy, get buy-in from platform and partnerships teams.',
      action: 'Researching Stripe, GitHub, and Twilio API versioning patterns. Drafting RFC with header-based versioning + sunset policy.',
      result: '',
      startDate: d(5),
      endDate: '',
      originalEstimateDays: 8,
      actualDays: 5,
      complicatingFactors: 'Strong opinions across teams—some want URL-based, others want header-based versioning.',
      technologies: ['REST', 'OpenAPI', 'API Gateway'],
      growthWins: 'Developing technical writing and consensus-building skills at staff level.',
      raci: ['responsible', 'accountable'] as RACIRole[],
      status: 'in-progress',
      impactLevel: 'medium',
    },
    {
      id: generateId(),
      title: 'Plan database sharding for orders service',
      createdAt: new Date(now.getTime() - 2 * 86400000).toISOString(),
      situation: 'Orders table approaching 500M rows. Query performance degrading, vertical scaling limits reached.',
      task: 'Design sharding strategy and migration plan for orders database.',
      action: '',
      result: '',
      startDate: d(2),
      endDate: '',
      originalEstimateDays: 15,
      actualDays: 0,
      complicatingFactors: 'Cross-shard queries needed for analytics. Must maintain ACID for order transactions.',
      technologies: ['PostgreSQL', 'Citus', 'PgBouncer'],
      growthWins: '',
      raci: ['consulted'] as RACIRole[],
      status: 'planned',
      impactLevel: 'critical',
    },
    {
      id: generateId(),
      title: 'Mentored 2 senior engineers on system design',
      createdAt: new Date(now.getTime() - 25 * 86400000).toISOString(),
      situation: 'Two senior engineers preparing for staff promotion. Needed system design mentorship.',
      task: 'Run weekly 1:1 design sessions covering distributed systems patterns relevant to their projects.',
      action: 'Created custom problem sets based on real company challenges. Reviewed their design docs and gave structured feedback. Practiced mock interviews.',
      result: 'Both engineers passed staff-level design interviews. One promoted in last cycle, other on track.',
      startDate: d(60),
      endDate: d(5),
      originalEstimateDays: 12,
      actualDays: 14,
      complicatingFactors: 'Scheduling conflicts with different timezones. Had to create async review format.',
      technologies: ['System Design', 'Distributed Systems', 'Technical Leadership'],
      growthWins: 'Discovered passion for mentorship. Improved own ability to articulate design trade-offs.',
      raci: ['responsible', 'informed'] as RACIRole[],
      status: 'completed',
      impactLevel: 'medium',
    },
  ];
}
